name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt.freeze'
      - run: python -m pip install -r requirements.txt.freeze
      - name: Install flake8, black, mypy and ruff
        run: |
          python -m pip install flake8
          python -m pip install black
          python -m pip install mypy
          python -m pip install ruff
      - name: Download and Convert Models
        run: |
          ct2-transformers-converter --model line-corporation/japanese-large-lm-3.6b-instruction-sft --low_cpu_mem_usage --output_dir line-sft --quantization int8 --force
          wget -P models https://huggingface.co/mmnga/ELYZA-japanese-Llama-2-7b-fast-instruct-gguf/resolve/main/ELYZA-japanese-Llama-2-7b-fast-instruct-q4_K_M.gguf
      - name: Lint with flake8
        run: python -m flake8 --exclude .venv/,.cache --max-line-length=88 .
      - name: Lint with black
        run: python -m black --check --extend-exclude .venv --diff --line-length 88 --skip-string-normalization .
      - name: Lint with mypy
        run: python -m mypy .
      - name: Lint with ruff
        run: |
          python -m ruff --format=github .
      - name: Test with pytest
        run: |
          python -m pytest
